source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'nanoUI_Example', :exclusive => true do
  pod 'nanoUI', :path => '../'
end

target 'nanoUI_Tests', :exclusive => true do
  pod 'nanoUI', :path => '../'
end
